name: Deploy frontend utils to AWS S3

on:
  push:
    paths:
      - 'node-red-contrib-rollun-utils/frontend-utils/**'
      - '.github/workflows/deploy-frontend-utils.yml'
    branches:
      - master

defaults:
  run:
    working-directory: node-red-contrib-rollun-utils/frontend-utils

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'frontend-utils.js'
