name: Deploy autodist api v062 to npm

on:
  push:
    paths:
      - 'node-red-contrib-rollun-autodist-api-v062/**'
    branches:
      - master

defaults:
  run:
    working-directory: node-red-contrib-rollun-autodist-api-v062

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node_modules
        uses: actions/cache@master
        id:
          cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package.json') }}

      - name: Install dependecies
        run: npm ci

      - name: Build
        run: npm run build

      - run: git fetch origin
      - run: npm --no-git-tag-version version $(git describe --tags --abbrev=0)
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
